version: '3.8'
services:
  postgres-container:
    image: postgres:15.2
    container_name: postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - database-network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hash_data
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5
  migration_hash_table:
    image: liquibase/liquibase:4.19.0
    networks:
      - database-network
    depends_on:
      - postgres-container
    volumes:
      - ./migrations:/app
    command: --defaultsFile=/app/dev.properties update


networks:
  database-network:
    name: "database-network"
